name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there! Thank you for opening an issue. We're happy to have you as a contributor. If you have any questions, please don't hesitate to ask. Let's work together to make this project even better!"
        pr-message: "Wow, thanks for submitting a pull request! We're excited to review your contribution and see how it can improve the project. Let us know if you have any questions or concerns. Thanks again for your help!"
